////////////////////////////////////////////////////////////////////
//
// RUSSIAN.H
// by Pavel Keyno, 2021
//
// Translation team from Old-Games.RU: Grongy, Веловояджер, Dimouse,
//				       Gunsliger7, kreol, Pyhesty, SlashNet
//
// Special thanks to Adam Biser for helping
//
////////////////////////////////////////////////////////////////////



#define QUITSUR	"Вы уверены, что хотите выйти\n"\
		"с этой великой игры?"

#define CURGAME	"В данный момент ты в игре.\n"\
		"Если продолжишь, то сотрёшь\n"\
		"старую игру. Ты согласен?"

#define GAMESVD	"В этом месте уже есть\n"\
		"сохранённая игра.\n"\
		"Перезаписать?"

#define ENDGAMESTR	"Уверен, что хочешь закончить\n"\
					"игру, в которую играешь?\n"\
					"(Y - да, N - нет):"

#define STR_NG	"Новая игра"
#define	STR_SD	"Звук"
#define	STR_CL	"Управление"
#define	STR_LG	"Загрузить игру"
#define	STR_SG	"Сохранить игру"
#define	STR_CV	"Размер окна"
#define	STR_VS	"Рекорды"
#define STR_EG	"Закончить игру"
#define	STR_BD	"Назад в демо"
#define STR_QT	"Выйти"

#define STR_LOADING	"Загрузка"
#define STR_SAVING	"Сохранение"

#define STR_GAME	"игру"
#define STR_DEMO	"демо"
#define STR_LGC		"Загрузить игру\n\""
#define STR_EMPTY	"пусто"
#define STR_CALIB	"Калибровка"
#define STR_JOYST	"джойстика"
#define STR_MOVEJOY	"Направь джойстик\nв верхний левый угол,\nнажми кнопку 0\n"
#define STR_MOVEJOY2	"Направь джойстик\nв нижний правый угол,\nнажми кнопку 1\n"
#define STR_ESCEXIT	"ESC - выход"

#define STR_NONE	"Отсутствует"
#define STR_NONEPLR	"Отсутствуют"
#define	STR_PC		"PC Speaker"
#define	STR_ALSB	"AdLib/Sound Blaster"
#define	STR_DISNEY	"Disney Sound Source"
#define	STR_SB		"Sound Blaster"

#define	STR_MOUSEEN	"Включить мышь"
#define	STR_JOYEN	"Включить джойстик"
#define	STR_PORT2	"Использовать порт 2"
#define	STR_GAMEPAD	"Включить Gravis GamePad"
#define	STR_SENS	"Чувствительность мыши"
#define	STR_CUSTOM	"Настроить управление"

#define	STR_DADDY	"Можно мне поиграть, папочка?"
#define	STR_HURTME	"Не делай мне больно."
#define	STR_BRINGEM	"Давайте всех сюда!"
#define	STR_DEATH	"Я воплощение Смерти!"

#define	STR_MOUSEADJ	"Чувствительность мыши"
#define STR_SLOW	"Медл."
#define STR_FAST	"Быстр."

#define	STR_CRUN	"Бег"
#define STR_COPEN	"Откр."
#define STR_CFIRE	"Огонь"
#define STR_CSTRAFE	"Стрейф"

#define	STR_LEFT	"Влево"
#define	STR_RIGHT	"Вправо"
#define	STR_FRWD	"Вперёд"
#define	STR_BKWD	"Назад"
#define	STR_THINK	"Считаю"

#define STR_SIZE1	"Стрелки - изменение размера окна"
#define STR_SIZE2	"ENTER - сохранение изменений"
#define STR_SIZE3	"ESC - отмена"

#define STR_YOUWIN	"Ты победил!"

#define STR_TOTALTIME	"Общее время"

#define STR_RATKILL	"Убийств       %"
#define STR_RATSECRET	"Секретов      %"
#define STR_RATTREASURE	"Сокровищ_     %"

#define STR_BONUS	"Бонус"
#define STR_TIME	"Время"
// RECORD character
#define STR_PAR		"@"

#define STR_RAT2KILL	"убийства          %"
#define STR_RAT2SECRET	"секреты_          %"
#define STR_RAT2TREASURE"сокровища_        %"

#define STR_DEFEATED	"повержен!"

#define STR_CHEATER1	"Теперь у тебя есть 100%"
#define STR_CHEATER2	"здоровья, 99 патронов и"
#define STR_CHEATER3	"оба ключа! Учти, что у тебя"
#define STR_CHEATER4	"практически не осталось"
#define STR_CHEATER5	"шансов добиться рекорда!"

#define STR_NOSPACE1	"Для сохранения не хватает"
#define STR_NOSPACE2	"свободного места на диске!"

#define STR_SAVECHT1	"Твой файл сохранения игры,"
#define STR_SAVECHT2	"скажем так, \"повреждён\". Но я"
#define STR_SAVECHT3	"всё равно позволю вам играть..."

#define	STR_SEEAGAIN	"Давай снова на это"
#define	STR_SEEAGRUS	"посмотрим!"

#define STR_AXISYDIS	"Выключить ось Y мыши"